---
- name: Create users and add them to the sudo group
  user:
    name: "{{ item.username }}"
    role: sudo
    shell: /bin/bash
    groups: "{{ user_groups }}"
    append: true
  loop: "{{ sudo_users }}"

- name: Create .ssh directory
  file:
    path: /home/{{ item.username }}/.ssh
    state: directory
    mode: 0700
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
  loop: "{{ sudo_users }}"

- name: Get the public key from github
  uri:
    url: "https://github.com/{{ item.username }}.keys"
    method: GET
    return_content: true
    dest: /home/{{ item.username }}/.ssh/authorized_keys
    mode: 0600
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
  loop: "{{ sudo_users }}"
  ignore_errors: true

- name: Touch the users file in sudoers.d directory
  file:
    path: "/etc/sudoers.d/{{ item.username }}"
    state: touch
    mode: 0440
    owner: root
    group: root
  loop: "{{ sudo_users }}"

- name: Insert/Update "User" configuration block in /etc/sudoers.d
  blockinfile:
    path: "/etc/sudoers.d/{{ item.username }}"
    block: |
      # User rules for {{ item.username }}
      {{ item.username }} ALL=NOPASSWD:ALL
  loop: "{{ sudo_users }}"
